---
title: "ML with R: Linear Regression"
author: "Suhas. P. K"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
    default_style: "dark"
    downcute_theme: "default"
---


```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
```


```{r datasets}
url <- "https://archive.ics.uci.edu/static/public/320/student+performance.zip"
destfile <- paste(getwd(),"student_data.zip", sep="/")

if (!file.exists(destfile)){
  download.file(url=url, 
                destfile = destfile)
  unzip ("student_data.zip", exdir = "./")
  unzip("student.zip", exdir = "./")
  
  file.remove("student_data.zip", "student.zip")
}


```


```{r}
df <- read.csv("student-mat.csv", sep = ";")
head(df)
```

```{r summary}
summary(df)
```


```{r check for NA}
anyNA(df)
```

```{r dataframe structure}
str(df)
```

```{r libraries, message=FALSE,warning=FALSE}
if (!require(ggplot2)){
  install.packages("ggplot2")
  library(ggplot2)
}

if (!require(ggdark)){
  install.packages("ggdark")
  library(ggdark)
}

if (!require(ggthemes)){
  install.packages("ggthemes")
  library(ggthemes)
}

if (!require(dplyr)){
  install.packages("dplyr")
  library(dplyr)
}

if (!require(corrgram)){
  install.packages("corrgram")
  library(corrgram)
}

if (!require(corrplot)){
  install.packages("corrplot")
  library(corrplot)
}

if (!require(caTools)){
  install.packages("caTools")
  library(caTools)
}
```

```{r correlation}
num.cols <- sapply(df,is.numeric)
cor.data <- cor( df[,num.cols])
head(cor.data)
```

```{r correlation visualize 1,echo=FALSE}
corrplot(cor.data, method = 'color')

```


```{r correlation visualization 2}
corrgram(df)

```

```{r correlation visualization 3}
corrgram(df, order = TRUE, lower.panel = panel.shade,
         upper.panel = panel.pie, text.panel = panel.txt)

```


```{r ggplot histogram}
ggplot(df, aes(x = G3)) + geom_histogram(bins = 20, alpha = 0.5,
                                         fill='green',color = 'black') + dark_theme_classic()
```


```{r split data}
set.seed(101)

sample <- sample.split(df$G3, SplitRatio = 0.7)
train <- subset(df, sample==TRUE)
test <- subset(df, sample==FALSE)

```

```{r linear regression model1}
model <- lm(G3~., data = train)
```

```{r model summary}
summary(model)
```

```{r residuals}
res <- residuals(model)
res <- as.data.frame(res)

ggplot(res,aes(res)) + geom_histogram(bins = 30, fill = 'red', color = 'white') + dark_theme_light()
```


```{r model plot}
plot(model)
```


```{r prediction}
G3.prediction <- predict(model, test)

results <- cbind(G3.prediction, test$G3)
colnames(results) <- c('predicted','actual')
results <- as.data.frame(results)

head(results)
```


```{r error handling}
# to handle negative prediction values
to_zero <- function(x){
  if (x < 0) {
    return(0)
  } else {
    return(x)
  }
}

results$predicted <- sapply(results$predicted, to_zero)

# mean square error
mse <- mean((results$actual - results$predicted)^2)

sse <- sum((results$predicted - results$actual)^2)
sst <- sum((mean(df$G3) - results$actual)^2)  
r2 <- 1 - sse/sst

print(r2)

```






```{r lm visual1}
plot_data <- data.frame(actual = results$actual, predicted = results$predicted)

# Scatter plot with smoother line and shaded confidence intervals
ggplot(plot_data, aes(x = actual, y = predicted)) +
  geom_point(color = "green", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", se = TRUE, color = "orange", fill = "white", alpha = 0.5) +
  labs(title = "Predicted vs Actual", x = "Actual Values", y = "Predicted Values") +
  dark_theme_light()
```


- If most of the points lie close to the smoother line and within the confidence intervals, it suggests a good fit between the actual and predicted values.

- If points are widely spread, especially outside the confidence intervals, it may indicate issues with the model's predictive performance







